stages:
  - build
  - deploy
  
build:
  image: node:14
  stage: build
  script:
  yarn run lint //checks all files with prettier
yarn run lint:fix //fixes all issues and leaves unstaged files
yarn run eslint //check all files with eslint
yarn run eslint:fix //fixes issues that can be resolved by eslint

    - yarn add prettier
    - npx prettier --check .

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - chmod 600 $IDRSA
    - apk update
    - apk add --update yarn openssh-client
    - yarn install
    - yarn build
    - ssh -i $IDRSA -o StrictHostKeyChecking=no $SKRAGGLE_USER@$SKRAGGLE_HOST "rm -rf ~/build/*"
    - scp -i $IDRSA -o StrictHostKeyChecking=no -r build/* $SKRAGGLE_USER@$SKRAGGLE_HOST:~/build/
  only:
    - develop